# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170328_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='kr_name',
            field=models.CharField(default='동아리명', help_text='동아리명 (한국어)', max_length=20),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='동아리명 (한국어)', max_length=20),
        ),
    ]
