# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20170331_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
