# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_category_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dongari',
            name='Title',
        ),
        migrations.AddField(
            model_name='dongari',
            name='kr_name',
            field=models.CharField(default='name', help_text='동아리명 (한국어)', max_length=100),
        ),
        migrations.AddField(
            model_name='dongari',
            name='name',
            field=models.CharField(default='name', help_text='Club Name(English)', max_length=100),
        ),
    ]
