# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 11:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20170402_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='dongari',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Dongari'),
        ),
    ]
