# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 11:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20170402_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dongari',
            name='category',
        ),
    ]
