# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 22:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_dongari_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dongari',
            old_name='content',
            new_name='description',
        ),
    ]
