# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 09:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20170402_2244'),
    ]

    operations = [
        migrations.CreateModel(
            name='Core',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_core', models.CharField(help_text='Root (English)', max_length=20)),
                ('kr_name_core', models.CharField(help_text='대분류 (한국어)', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='root',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Core'),
        ),
    ]
